package sumaApp;


/**
* sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* domingo 15 de abril de 2012 04H55' CDT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
