package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* miércoles 18 de abril de 2012 08H48' CDT
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  int restar (int primernumero, int segundonumero);
  int multiplicar (int primernumero, int segundonumero);
  int dividir (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
